/********************************************************************
* CDominoDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error CDominoDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableCDominoDict();
extern void G__cpp_setup_inheritanceCDominoDict();
extern void G__cpp_setup_typetableCDominoDict();
extern void G__cpp_setup_memvarCDominoDict();
extern void G__cpp_setup_globalCDominoDict();
extern void G__cpp_setup_memfuncCDominoDict();
extern void G__cpp_setup_funcCDominoDict();
extern void G__set_cpp_environmentCDominoDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "CDomino.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CDominoDictLN_TClass;
extern G__linked_taginfo G__CDominoDictLN_TBuffer;
extern G__linked_taginfo G__CDominoDictLN_TMemberInspector;
extern G__linked_taginfo G__CDominoDictLN_TObject;
extern G__linked_taginfo G__CDominoDictLN_TNamed;
extern G__linked_taginfo G__CDominoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__CDominoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CDominoDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__CDominoDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CDominoDictLN_TAttLine;
extern G__linked_taginfo G__CDominoDictLN_TAttFill;
extern G__linked_taginfo G__CDominoDictLN_TAttMarker;
extern G__linked_taginfo G__CDominoDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__CDominoDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__CDominoDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CDominoDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__CDominoDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__CDominoDictLN_TGraph;
extern G__linked_taginfo G__CDominoDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__CDominoDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__CDominoDictLN_CDomino;
extern G__linked_taginfo G__CDominoDictLN_COUNT;

/* STUB derived class for protected member access */
